apiVersion: v1
kind: ConfigMap
metadata:
  name: polsearch-api-config
  namespace: praveen
  labels:
    app.kubernetes.io/name: polsearch-api
data:
  PORT: "3000"
  LOG_LEVEL: "info"
  SEARCH_TIMEOUT_SECS: "30"
  AWS_ENDPOINT_URL: "https://nyc3.digitaloceanspaces.com"
  AWS_REGION: "nyc3"
